### ISSUE TITLE
关于 Quantumult X 域名相关 filter 规则语法

### ISSUE THREAD

**Issue by bdbai** [HotKids/Rules#6]
注意到 /Quantumult/X/Filter 中域名相关的 filter 规则使用了类似 Surge/Clash 的语法（比如 `DOMAIN-SUFFIX`）而不是 Quantumult X 官方示例中使用的语法（比如 `host-suffix`），想问下这样有什么特殊考虑？可以按预期正常工作吗？

**Comment by HotKids** [comment]
可以正常工作
